#!/bin/bash
# ~/.local/bin/niri-custom-launcher

opciones="📊 Btop\n💻 Fastfetch\n🌐 nmtui\n🌄 ConvertBackgroundToWebp"

selected=$(echo -e "$opciones" | fuzzel --dmenu -l 4 -p "🚀 Comando: ")

case "$selected" in
"📊 Btop")
  kitty btop
  ;;
"💻 Fastfetch")
  kitty bash -c 'fastfetch; echo ""; read -p "Presiona Enter para cerrar..."'
  ;;
"🌐 nmtui")
  kitty nmtui
  ;;
"🌄 ConvertBackgroundToWebp")
  ~/.local/bin/conver-Background-to-webp.sh
  ;;
esac
