#!/bin/bash

# Evita lanzar dos instancias si le das doble bind
pgrep -x swaylock >/dev/null && exit 0

# Ejecuta swaylock en segundo plano
swaylock &

sleep 0.3

# Apaga la pantalla OLED antes de bloquear (protege burn-in)
niri msg action power-off-monitors &
systemctl suspend
