#!/bin/bash

echo "UPGRADING APT PACKAGES:"
sleep 1
sudo apt update && sudo apt upgrade

echo "UPGRADING FLATPAK PACKAGES:"
sleep 1
flatpak update

echo "UPGRADING NIX PACKAGES:"
sleep 1
nix profile upgrade --all