#!/bin/bash
# ~/.local/bin/niri-custom-launcher

opciones="📊 Btop\n💻 Fastfetch\n🌐 nmtui"

selected=$(echo -e "$opciones" | fuzzel --dmenu -l 4 -p "🚀 Comando: ")

case "$selected" in
"📊 Btop")
  alacritty -e btop
  ;;
"💻 Fastfetch")
  alacritty -e bash -c 'fastfetch; echo ""; read -p " --- Exit With Enter"'
  ;;
"🌐 nmtui")
  alacritty -e nmtui
  ;;
esac
